services:
  app:
    image: ghcr.io/${GITHUB_REPOSITORY}/my-app:${IMAGE_TAG:-latest}
    container_name: grape-server
    restart: unless-stopped
    expose:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_URL}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}


  nginx:
    image: nginx:latest
    container_name: grape-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app

volumes:
  db_data: