services:
  cloud-sql-proxy:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest
    restart: unless-stopped
    command:
      - "--address=0.0.0.0"
      - "--port=5432"
      - "--private-ip"
      - "--health-check"
      - "--http-address=0.0.0.0"
      - "--http-port=9090"
      - "${INSTANCE_CONNECTION_NAME}"
    healthcheck:
      test: [ "CMD", "/cloud-sql-proxy", "--version" ]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    image: ghcr.io/${GITHUB_REPOSITORY}/my-app:${IMAGE_TAG:-latest}
    container_name: grape-server
    restart: on-failure
    expose:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_URL}/${DB_NAME}?sslmode=disable
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      APPLE_BUNDLE_ID: ${APPLE_BUNDLE_ID}
    depends_on:
      cloud-sql-proxy:
        condition: service_healthy
    build: .
    volumes:
      - ./logs:/logs


  nginx:
    image: nginx:latest
    container_name: grape-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app
      - grafana
  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - ./logs:/logs
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
